community/weechat/build
community/weechat/depends

Sadly WeeChat requires GnuTLS for SSL/TLS connections.
This PR adds GnuTLS to WeeChat.

weechat: added gnutls

---

community/emacs/build
community/emacs/depends

Change from GTK to Athena toolkit (emacs is well known to not have a proper gtk implementation and the Athena toolkit is more performant)

change build and depends: emacs 26.3

---

community/emacs/build

@dylanaraps I dropped the ball on this. Our Emacs won't build as is currently unleess we add this configure option.

emacs fix: use with-xpm=no

---

community/libxdg-basedir/build
community/libxdg-basedir/depends

Turns out this package's source *does* need to generate `./configure` from automake, to make matters worse, last release was in 2012.

libxdg-basedir: use automake

---

community/emacs-nox/build
community/emacs-nox/depends

1. I have spent a lot of time trying to understand the current Emacs security situation, and to the best of my understanding, Emacs development teams favor gnutls to be the default tls, and all other implementations inside Emacs have now gone unmaintained (probably due to being non-gpl licensed), and coming up in Emacs 27 this will be the case even more so. I'm ensuring that our Emacs builds are building explicitly with gnutls support.
2. I also enabled mouse clicking support when using an X11 terminal emulator
3. I enabled libxml2 support for emacs-nox, which will allow use of the eww web browser, which is very nice for reading documentation directly in the Emacs editor.
4. Improve startup times by ~1 second by decreasing garbage collection frequency to every 50 MB instead of the default …

Improve emacs-nox security settings, add better default xterm settings

---

community/emacs/build

1. I have spent a lot of time trying to understand the current Emacs security situation, and to the best of my understanding, Emacs development teams favor gnutls to be the default tls, and all other implementations inside Emacs have now gone unmaintained (probably due to being non-gpl licensed), and coming up in Emacs 27 this will be the case even more so. I'm ensuring that our Emacs builds are building explicitly with gnutls support.
2. Improve startup times by ~1 second by decreasing garbage collection frequency to every 50 MB instead of the default 0.76MB (Emacs is optimized for very old computers by default) AND by toggling off package.el (can be turned back on by the user easily, no point in penalizing all Emacs users with a slow startup by having using package.el by always-on by …

improve emacs' gnutls settings

---

community/sbase/build

`file /usr/bin/sbase-box` indicated dynamic linking. this is a fix, also properly respecting environmental flags (though overridden by the defaults in config.mk).

sbase: respect environmental vars, fix static linking

---

community/fff/depends

Can't open files by pressing `Return`
- `file` is missing as dep, installed it solved the issue.
- `file` added in `depends`

fff: fix depends, file is missing

---

community/gnupg2/build

gnupg2: Keep --enable-gpg-is-gpg2, Add gpg symlinks sans "2" for alternatives

---

community/gdb/build

gdb 9.1 needs a separate build directory, apparently -- it refuses to
build from the source dir. To fix this, I've created a `_build` dir
(since `build` already exists). This should hopefully cause no problems.

gdb: fix build

---

community/dosbox/build

Read: https://k1ss.org/guidestones.txt
Reason for change:
I found Dosbox fails to build while testing out on a clean install.  I had "libglu" installed on my machine after working on something else.  libglu is needed by Dosbox, unless --disable-opengl is specified.
I have libglu ready to add to the repo if required, but since Dosbox can do without it (and didn't seem to run any slower without it when I tried), I thought it would be preferable to avoid a new dependency if it's not essential.

Fix build: disable OpenGL support

---

community/mpd/depends

Since boost is linked statically, mpd does not require it as a runtime dependency. Thanks a lot to @ioraff for pointing this out.

mpd: require boost as a make dependency

---

community/tcc/build

tcc's configure uses gcc as default compiler.
Allow user choice of c compiler using CC environment variable (tcc can compile itself).

tcc: use CC as compiler

---

community/boost/build

Fixes #524 . Manifest pasted on termbin for being too big.
See <https://termbin.com/g867>

boost: don't link statically

---

community/font-awesome/build
community/font-awesome/post-install

Added TTF fonts and added a post-install script
```
/var/db/kiss/installed/font-awesome/version
/var/db/kiss/installed/font-awesome/sources
/var/db/kiss/installed/font-awesome/post-install
/var/db/kiss/installed/font-awesome/manifest
/var/db/kiss/installed/font-awesome/checksums
/var/db/kiss/installed/font-awesome/build
/var/db/kiss/installed/font-awesome/
/var/db/kiss/
/var/db/
/var/
/usr/share/fonts/TTF/fa-solid-900.ttf
/usr/share/fonts/TTF/fa-regular-400.ttf
/usr/share/fonts/TTF/fa-brands-400.ttf
/usr/share/fonts/TTF/
/usr/share/fonts/OTF/Font Awesome 5 Free-Solid-900.otf
/usr/share/fonts/OTF/Font Awesome 5 Free-Regular-400.otf
/usr/share/fonts/OTF/Font Awesome 5 Brands-Regular-400.otf
/usr/share/fonts/OTF/
/usr/share/fonts/
/usr/share/
/usr/
```

font-awesome: added TTF fonts and post-install script

---

community/wireguard-tools/build

Makefile will now install wg-quick if it finds bash on the system.

wireguard-tools: remove unnecessary build flags

---

community/nano/build

Fixed --sysconfdir in nano build options. Now set to /etc.

---

community/libmpdclient/depends
community/mpd/build

Resolves #756
There isn't actually a circular dependency between `mpd` and
`libmpdclient`. It seems that `libmpdclient` doesn't actually
depend on `mpd`. Changes here make sure that neither of them
depend on each other by,
* Setting an option in meson build for mpd to disable linking to libmpdclient.
* Removing the listed mpd dependency from libmpdclient.
Manifests are the same as previous.

mpd-libmpdclient: fix circular dependency

---

community/gst-plugins/depends
community/gstreamer/depends

This resolves #774 . No manifest change is made.
Also, I have noticed that gst-plugins depend on linux-headers. So I have
added that as well.

gstreamer gst-plugins: add missing dependencies

---

community/qt5-webengine/build

---
Ten hours later, it's fixed.
```
http://ix.io/2gbH
```

qt5-webengine build fix for GCC 10

---

community/sbase/build

We no longer need to unlink sbase-tar.

sbase: do not unlink tar

---

community/boost/depends

boost: add missing linux-headers dependency

---

community/qt5-webengine/depends
community/qt5/depends

qt5 and qt5-webengine require linux-headers to make.

qt5{-webengine} updated deps

---

community/bspwm/build

I can't confirm the current problem since I don't use GCC, but if sxhkd is affected, then bspwm might be affected too. Dylan, can you check if the current packaging without CFLAGS fix work? If it works, then you can close this PR without merging. Thanks.
No changes.

bspwm: fix gcc 10 (Untested on GCC)

---

community/ii/build

Fixes /usr/bin/ii permissions from 775 to 755
```
/var/db/kiss/installed/ii/version
/var/db/kiss/installed/ii/sources
/var/db/kiss/installed/ii/manifest
/var/db/kiss/installed/ii/checksums
/var/db/kiss/installed/ii/build
/var/db/kiss/installed/ii/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/ii.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/doc/ii/README
/usr/share/doc/ii/LICENSE
/usr/share/doc/ii/FAQ
/usr/share/doc/ii/CHANGES
/usr/share/doc/ii/
/usr/share/doc/
/usr/share/
/usr/bin/ii
/usr/bin/
/usr/
```

ii: fix permissions

---

community/sbase/build

These changes don't make a difference in the manifest. The sed call to `config.mk` was unnecessary.
The issue was with the Makefile. It rebuilds sbase-box when running `sbase-box-install`. Since we do not normally add LDFLAGS to the `install` part, the outcome wasn't a static binary.
I am also sending a patch to the mailing-list fixing this issue, so if the patch is accepted, I will be reverting to the clean-looking format.
```
make sbase-box
make sbase-box-install
```

sbase: proper static linking

---

community/sbase/build

Upstream has taken in my changes, so I have reverted to this clean looking format. Again, manifest isn't changed.

sbase: apply changes for the new revision

---

community/qt5/depends

`qt5` requires `icu` until the (forthcoming) bug report with upstream is resolved. 
Closes #972

qt5 requires icu

---

community/qt5/depends

As per the resolution of [this](https://bugreports.qt.io/browse/QTBUG-85453) bug report, `qt5` only required `icu` because `kiss` set `LC_ALL=C`. As this change has been reverted, we can revert our `icu` requirement.

qt5 no longer requires icu

---

community/fftw/build

Change made the names of library files change, breaking dependencies. 

fftw: undo change to build flags (breaks deps)

---

community/uemacs/build
community/uemacs/depends

This change increases the size of em ~40KB. I have also forgotten to add ncurses as a dependency. Since we are now building statically, ncurses is a make dependency here.

uemacs: add missing dependency and build statically

---

community/qt5-webengine/build

This PR fixes a build error introduced with the latest version of `bison` (3.7+). 
---
```
http://ix.io/2t4d
```

qt5-webengine now builds with latest bison

---

community/qt5-x11extras/depends

`qt5-x11extras` requires `perl` at build time.

qt5-x11extras has perl make dep

---

community/usbutils/build

usbutils: fix missing slash in sed

---

community/emacs-nox/checksums
community/emacs-nox/sources
community/emacs-nox/version

I have noticed that the emacs-nox package was outdated. Since emacs-nox is emacs with no X support, I have thought that it is best to just make the {sources,checksums,version} files to be symbolic links to the main emacs package.

emacs-nox: track the main emacs package for version and sources

---

community/cryptsetup/depends

Fixes https://freenode.logbot.info/kisslinux/20200903#c4973634
Irrelevant.

cryptsetup: add pkgconf dep

---

community/nettle/build

(`kiss manifest <pkg>`)
```
/var/db/kiss/installed/nettle/version
/var/db/kiss/installed/nettle/sources
/var/db/kiss/installed/nettle/manifest
/var/db/kiss/installed/nettle/depends
/var/db/kiss/installed/nettle/checksums
/var/db/kiss/installed/nettle/build
/var/db/kiss/installed/nettle/
/var/db/kiss/
/var/db/
/var/
/usr/lib/pkgconfig/nettle.pc
/usr/lib/pkgconfig/hogweed.pc
/usr/lib/pkgconfig/
/usr/lib/libnettle.so.8.0
/usr/lib/libnettle.so.8
/usr/lib/libnettle.so
/usr/lib/libnettle.a
/usr/lib/libhogweed.so.6.0
/usr/lib/libhogweed.so.6
/usr/lib/libhogweed.so
/usr/lib/libhogweed.a
/usr/lib/
/usr/include/nettle/yarrow.h
/usr/include/nettle/xts.h
/usr/include/nettle/version.h
/usr/include/nettle/umac.h
/usr/include/nettle/twofish.h
/usr/include/nettle/siv-cmac.h …
```

nettle: enable static libraries

---

community/iproute2/build

`iproute2`'s makefile uses hardcoded `gcc` in one place even if it should use at least `$CC`. if gcc is installed you get a frankenbuild with mixed `$CC` ( clang ) and `gcc`. This change fixes this.

iproute2: enforce --prefix/usr and fix build on clang only systems

---

community/pciutils/build

Build and install shared libraries as well. Closes #1233 
(`kiss manifest <pkg>`)
```
/var/db/kiss/installed/pciutils/version
/var/db/kiss/installed/pciutils/sources
/var/db/kiss/installed/pciutils/manifest
/var/db/kiss/installed/pciutils/depends
/var/db/kiss/installed/pciutils/checksums
/var/db/kiss/installed/pciutils/build
/var/db/kiss/installed/pciutils/
/var/db/kiss/choices/pciutils>usr>bin>lspci
/var/db/kiss/choices/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/update-pciids.8
/usr/share/man/man8/setpci.8
/usr/share/man/man8/lspci.8
/usr/share/man/man8/
/usr/share/man/man7/pcilib.7
/usr/share/man/man7/
/usr/share/man/man5/pci.ids.5
/usr/share/man/man5/
/usr/share/man/
/usr/share/hwdata/pci.ids.gz
/usr/share/hwdata/
/usr/share/
/usr/lib/pkgconfig/libpci.pc …
```

pciutils: build and install shared libraries

---

community/pciutils/build

Closes #1280 
(`kiss manifest <pkg>`)
```
/var/db/kiss/installed/pciutils/version
/var/db/kiss/installed/pciutils/sources
/var/db/kiss/installed/pciutils/manifest
/var/db/kiss/installed/pciutils/depends
/var/db/kiss/installed/pciutils/checksums
/var/db/kiss/installed/pciutils/build
/var/db/kiss/installed/pciutils/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man8/update-pciids.8
/usr/share/man/man8/setpci.8
/usr/share/man/man8/lspci.8
/usr/share/man/man8/
/usr/share/man/man7/pcilib.7
/usr/share/man/man7/
/usr/share/man/man5/pci.ids.5
/usr/share/man/man5/
/usr/share/man/
/usr/share/hwdata/pci.ids.gz
/usr/share/hwdata/
/usr/share/
/usr/lib/libpci.so.3.7.0
/usr/lib/libpci.so.3
/usr/lib/libpci.a
/usr/lib/
/usr/bin/update-pciids
/usr/bin/setpci
/usr/bin/lspci
/usr/bin/ …
```

pciutils: fix building shared libraries

---

community/minisign/depends

Required by minisign's cmake build script.
No difference.

minisign: add pkgconf as an explicit make dep

---

community/qemu/depends

pkgconf is no longer an implicit dependency.
---

Add pkgconf as dependency

---

community/libtorrent/depends

Add build-time dependency on pkgconf, as this is no longer in core.
This is in relation to issue #1311

libtorrent: Add depends

---

community/cups-filters/build
community/cups-filters/depends

This PR fixes to issues:
- A fix were integrated in the `build` file, but it didn't work anymore (issue https://github.com/kisslinux/community/issues/1350).
- `pkgconf` is now added has a build dependency (issue https://github.com/kisslinux/community/issues/1311)

Cups filters: build and dependencies modified

---

community/w3m/depends

Added `pkgconf` as a make dependency per issue #1311.
On a side note, I noticed on Repology the version changed to 0.5.3pl38 (from 0.5.3). I looked at the source (https://github.com/tats/w3m) and on Repology and believe this to be the same release currently used. It looks like only OpenBSD is using this version name currently.
Should I bump the version so that it shows up as up-to-date on Repology or leave it as-is?

w3m: add pkgconf as make dependency

---

community/qt5-webengine/build

`qt5-webengine` no longer needs the fix for `bison`!
```
/var/db/kiss/installed/qt5-webengine/version
/var/db/kiss/installed/qt5-webengine/sources
/var/db/kiss/installed/qt5-webengine/patches/0032-chromium-musl-sandbox.patch
/var/db/kiss/installed/qt5-webengine/patches/0031-chromium-musl-portable-msghdr.patch
/var/db/kiss/installed/qt5-webengine/patches/0030-chromium-musl-execinfo.patch
/var/db/kiss/installed/qt5-webengine/patches/0023-chromium-musl-pread-pwrite.patch
/var/db/kiss/installed/qt5-webengine/patches/0022-chromium-musl-elf_reader.cc-include-sys-reg.h-to-get.patch
/var/db/kiss/installed/qt5-webengine/patches/0021-chromium-musl-Use-_fpstate-instead-of-_libc_fpstate-.patch
/var/db/kiss/installed/qt5-webengine/patches/0020-chromium-musl-Adjust-default-pthread-stack-size.patch …
```

qt5-webengine builds with bison 3.7 perfectly fine now

---

community/qt5-webchannel/depends

`qt5-webchannel` has a `perl` dep that slipped through the cracks.

qt5-webchannel: perl is a make depend

---

community/irssi/build
community/irssi/depends

irssi: remove libgcrypt dependency
