kisslinux/community

community/slock/depends

- [ x ] Latest upstream version.
- [ x ] I agree to maintain this package (**required**).
- [ x ] I agree to notify KISS if I can no longer maintain this package (**required**).

Remove "make" from depends file

---

community/coreutils/build

coreutils: use export CFLAGS

---

community/sbase/build
community/ubase/build

ubase: use CFLAGS

---

community/sbase/build

sbase: use CFLAGS

---

community/gnugrep/build

gnugrep: use export CFLAGS

---

community/nawk/build

nawk: use export CFLAGS

---

community/gawk/build

gawk: use export CFLAGS

---

community/mksh/build

mksh: use CFLAGS

---

community/emacs/build

emacs: disable svg images

---

community/pcre/build

pcre: add UTF-8 support

---

community/libxaw3d/depends

add needed dependencies for libxaw3d

---

community/opendoas/files/doas.conf

needs to`keepenv` from earlier declared environment variables

doas: fix kiss env

---

community/pinentry/build

pinentry: add /usr prefix to build

---

community/sic-git/checksums
community/sic-git/sources

sic-git: change source

---

community/nawk/build

nawk: update build for alternatives

---

community/patch/build

patch: update build for alternatives

---

community/gnugrep/build

gnugrep: update build for alternatives

---

community/findutils/build

findutils: update build for alternatives

---

community/diffutils/build

diffutils: update build for alternatives

---

community/dash/build

dash: update build for alternatives

---

community/gawk/build

gawk: update build for alternatives

---

community/coreutils/build

coreutils: update build for alternatives

---

community/gtar/build

gtar: update build for alternatives

---

community/webkit2gtk/depends

I apologize for not noticing it before.

webkit2gtk: fix depends

---

community/netsurf/build
community/netsurf/depends

netsurf: add missing gperf to make depends, fixes #320

---

community/emacs/build

I was an overzealous package maintainer, forgive me

emacs: remove non-default settings

---

community/emacs-nox/build

I was an overzealous package maintainer, forgive me

emacs-nox: remove non-default settings

---

community/tcl/build

tcl: fix symlink after install

---

community/gtar/build

gtar: remove FORCE_UNSAFE_CONFIGURE

---

community/coreutils/build

coreutils: remove FORCE_UNSAFE_CONFIGURE

---

community/tcl/build

Read: <getkiss.org/guidestones.txt>
My apologies. This PR is tested.

tcl: fix build

---

community/emacs-nox/build
community/emacs-nox/depends

Read: <getkiss.org/guidestones.txt>

emacs-nox: remove systemd cruft, sort depends

---

community/emacs-git/build
community/emacs-git/depends

Read: <getkiss.org/guidestones.txt>

emacs-git: remove systemd cruft, sort depends

---

community/pciutils/build

Read: https://k1ss.org/guidestones.txt

pciutils: fixes #395

---

community/lua/build

---
Remove executable rights of lua.pc file.

fix lua rights - thanks to paper

---

community/nettle/build

nettle: remove texinfo dependency

---

community/libcap/build

libcap: disable GOLANG

---

community/libcap/build

libcap: PKGCONFIGDIR=/usr/lib closes #499

---

community/qrencode/depends

qrencode: yeet unneeded build deps

---

community/usbutils/build
community/usbutils/depends

usbutils: add eudev to depends, remove make requirement for bash

---

community/qt5-declarative/depends

modified:   depends
---
```
http://ix.io/2gbE
```

qt5-declarative requires python to make

---

community/zathura/depends

zathura: file dependency added

---

community/sbase/build
community/sbase/checksums
community/sbase/patches/tar-dash-remove.patch
community/sbase/sources

sbase: apply patch for dashless tar usage

---

community/sdl2/depends

sdl2: add missing linux-headers dependency

---

community/gst-plugins-base/depends

gst-plugins-base: add linux-headers as a make dependency

---

community/sxhkd/build

No changes. As reported by ectlunya on IRC.

sxhkd: fix gcc 10

---

community/openjpeg2/depends

openjpeg2: Update depends for lcms name change

---

community/gst-plugins/depends

gst-plugins: rename lcms2 to lcms

---

community/cups-filters/depends

cups-filters: depedency of lcms2 renamed to lcms

---

community/sdl/depends

sdl: change maintainer, add missing depends: linux-headers

---

community/wmutils/build

Read: https://k1ss.org/wiki/kiss/style-guide
---
```
/var/db/kiss/installed/wmutils/version
/var/db/kiss/installed/wmutils/sources
/var/db/kiss/installed/wmutils/manifest
/var/db/kiss/installed/wmutils/depends
/var/db/kiss/installed/wmutils/checksums
/var/db/kiss/installed/wmutils/build
/var/db/kiss/installed/wmutils/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/xmrs.1
/usr/share/man/man1/xmmv.1
/usr/share/man/man1/wtp.1
/usr/share/man/man1/wtf.1
/usr/share/man/man1/wrs.1
/usr/share/man/man1/wname.1
/usr/share/man/man1/wmv.1
/usr/share/man/man1/wmutils.1
/usr/share/man/man1/wmp.1
/usr/share/man/man1/wew.1
/usr/share/man/man1/wattr.1
/usr/share/man/man1/slw.1 …
```

Fix manpages.

---

community/boost/sources

boost: fix source

---

community/strace/depends

strace depends: Add linux-headers

---

community/netsurf-fb/build

```
/var/db/kiss/installed/netsurf-fb/version
/var/db/kiss/installed/netsurf-fb/sources
/var/db/kiss/installed/netsurf-fb/manifest
/var/db/kiss/installed/netsurf-fb/depends
/var/db/kiss/installed/netsurf-fb/checksums
/var/db/kiss/installed/netsurf-fb/build
/var/db/kiss/installed/netsurf-fb/
/var/db/kiss/
/var/db/
/var/
/usr/share/netsurf-fb/welcome.html
/usr/share/netsurf-fb/quirks.css
/usr/share/netsurf-fb/netsurf.png
/usr/share/netsurf-fb/licence.html
/usr/share/netsurf-fb/internal.css
/usr/share/netsurf-fb/default.css
/usr/share/netsurf-fb/credits.html
/usr/share/netsurf-fb/adblock.css
/usr/share/netsurf-fb/Messages
/usr/share/netsurf-fb/
/usr/share/
/usr/bin/netsurf-fb
/usr/bin/
/usr/
```

netsurf-fb: update build

---

community/boost/build

boost: fix build

---

community/fftw/build

fftw: enable float option in build file

---

community/tuitube/checksums

tuitube: fix checksums

---

community/lvm2/build
community/lvm2/depends

lvm2: dynamically check udev

---

community/gc/sources

gc: Change source from hboehm.info/gc to https://github.com/ivmai/bdwgc

---

community/emacs-git/checksums
community/emacs-git/sources

emacs-git: bump to emacs-28 branch

---

community/bubblewrap/build

bubblewrap: fix build file #1151

---

community/libcap/build

lipcap: fix for #1232

---

community/seatd/depends

seatd: added missing meson dependency

---

community/transmission/depends

transmission: add pkgconf make depends

---

community/girara/depends

Fix issue https://github.com/kisslinux/community/issues/1311.

Girara: pkgconf added as dependency

---

community/zathura/depends

Fix issue https://github.com/kisslinux/community/issues/1311

zathura: pkgconf dependency added

---

community/glib-networking/depends
community/gnutls/depends
community/libsoup/depends

Added `pkgconf` dependencies for the change stated in #1311

various packages: add pkgconf dependency

---

community/webkit2gtk/build

Various changes for webkit2gtk. Fixes #1390, fixes #1391

Webkitgtk changes

---

community/alsa-plugins/depends

alsa-plugins: add pkgconf make dependency

---

community/picom/depends

Partial fix for #1311.
Irrelevant.

picom: add pkgconf dep

---

community/py-sip/build

py-sip: fix python include dir due python update

---

community/youtube-dl/sources

Please have a look at the repo before merging, it seems to me to be a reliable fork of `youtube-dl`. 
I hope it fixes the checksum problem.

youtube-dl: update sources

---

community/parted/depends

parted: add util-linux as dependency

---

community/dejavu-ttf/build

Package adopted, see https://github.com/kisslinux/community/issues/1460

dejavu-ttf: adopted package

---

community/nfs-utils/build

nfs-utils: update build flags

---

community/libedit/build

libedit: patch for gcc-less systems
